object Dependencies {
    const val applicationId = "ru.petrolplus.pos"
    const val namespace = "ru.petrolplus.pos"
    const val namespaceUi = "ru.petrolplus.pos.ui"
    const val namespaceUtil = "ru.petrolplus.pos.util"
    const val namespaceCore = "ru.petrolplus.pos.core"
    const val namespaceMainScreen = "ru.petrolplus.pos.mainscreen"
    const val namespaceP7Lib = "ru.petrolplus.pos.p7Lib"
    const val namespaceNetwork = "ru.petrolplus.pos.network"
    const val namespaceNetworkWorker = "ru.petrolplus.pos.networkworker"
    const val namespaceNetworkApi = "ru.petrolplus.pos.networkApi"
    const val namespaceP7LibApi = "ru.petrolplus.pos.p7LibApi"
    const val namespaceEvotorSdk = "ru.petrolplus.pos.evotorsdk"
    const val namespaceSdkApi = "ru.petrolplus.pos.sdkapi"
    const val namespaceRoom = "ru.petrolplus.pos.room"
    const val namespaceResources = "ru.petrolplus.pos.resources"
    const val namespacePersistence = "ru.petrolplus.pos.persitence"
    const val namespacePrinterApi = "ru.petrolplus.pos.printerapi"
    const val namespaceEvatorPrinter = "ru.petrolplus.pos.evatorprinter"

    const val androidApplication = "com.android.application"
    const val kotlinAndroid = "android"
    const val workKtx = "androidx.work:work-runtime-ktx"
    const val testInstrumentationRunner = "testInstrumentationRunner"
    const val gmsAuth = "com.google.android.gms:play-services-auth"
    const val bcprovJdk = "org.bouncycastle:bcprov-jdk15on"
    const val coreKtx = "androidx.core:core-ktx"
    const val appcompat = "androidx.appcompat:appcompat"
    const val androidMaterial = "com.google.android.material:material"
    const val constraintlayout = "androidx.constraintlayout:constraintlayout"
    const val junit = "junit:junit"
    const val gsonConverter = "com.squareup.retrofit2:converter-gson"
    const val gson = "com.google.code.gson:gson"
    const val extJunit = "androidx.test.ext:junit"
    const val espresso = "androidx.test.espresso:espresso-core"
    const val dagger = "com.google.dagger:dagger"
    const val daggerCompiler = "com.google.dagger:dagger-compiler"
    const val androidxNavigation = "androidx.navigation"
    const val kotlinxCoroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android"
    const val kotlinxCoroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core"

    const val activityCompose = "androidx.activity:activity-compose"
    const val composeFoundation = "androidx.compose.foundation:foundation"
    const val annotation = "androidx.annotation:annotation"

    const val composeUi = "androidx.compose.ui:ui"
    const val composeMaterial = "androidx.compose.material:material"
    const val composeUiUtil = "androidx.compose.ui:ui-util"
    const val composeUiToolPreview = "androidx.compose.ui:ui-tooling-preview"
    const val composeUiTool = "androidx.compose.ui:ui-tooling"
    const val composeRuntime = "androidx.compose.runtime:runtime"
    const val composeLiveDate = "androidx.compose.runtime:runtime-livedata"

    const val composeNavigation = "androidx.navigation:navigation-compose"
    const val composeConstraint = "androidx.constraintlayout:constraintlayout-compose"
    const val lifecycleRuntime = "androidx.lifecycle:lifecycle-runtime-ktx"
    const val lifecycleViewModel = "androidx.lifecycle:lifecycle-viewmodel-compose"

    const val buildTools = "com.android.tools.build:gradle"

    const val retrofit = "com.squareup.retrofit2:retrofit"
    const val okhttpProfiler = "com.localebro:okhttpprofiler"
    const val okhttLoggingInterceptor = "com.squareup.okhttp3:logging-interceptor"
    const val evotor = "com.github.evotor:integration-library"

    const val roomCompiler = "androidx.room:room-compiler"
    const val roomKtx = "androidx.room:room-ktx"
    const val roomTesting = "androidx.room:room-testing"

    const val detekt = "io.gitlab.arturbosch.detekt"
    const val spotless = "com.diffplug.spotless"
}

object Versions {
    const val minSdkVersion = 23
    const val targetSdk = 33
    const val versionCode = 1
    const val kotlinCompilerExtensionVersion = "1.3.1"
    const val versionName = "1.0"
    const val workKtx = "2.8.1"
    const val androidApplication = "7.3.1"
    const val androidAnnotation = "1.2.0"
    const val kotlinAndroid = "1.7.10"
    const val retrofit = "2.9.0"
    const val gsonConverter = "2.9.0"
    const val okhttpProfiler = "1.0.8"
    const val okhttLoggingInterceptor = "4.11.0"
    const val gmsAuth = "20.6.0"
    const val bcprovJdk = "1.67"
    const val coreKtx = "1.5.0"
    const val appcompat = "1.5.0"
    const val androidMaterial = "1.8.0"
    const val constraintlayout = "2.1.4"
    const val junit = "4.13.2"
    const val extJunit = "1.1.5"
    const val espresso = "3.5.1"
    const val dagger = "2.45"
    const val compileSdkVersion = "android-33"
    const val androidxNavigation = "2.5.3"
    const val kotlinxCoroutines = "1.6.4"

    const val compose = "1.0.5"
    const val activityCompose = "1.4.0"
    const val composeActivity = "1.4.0"
    const val annotation = "1.2.0"
    const val composeNavigation = "2.4.0-alpha10"
    const val composeConstraint = "1.0.0-rc01"
    const val lifecycle = "2.5.1"
    const val gson = "2.10.1"
    const val evotor = "v0.6.03"
    const val room = "2.5.2"

    const val spotless = "6.21.0"
    const val ktlint = "0.50.0"
    const val detekt = "1.17.0"
}